version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app1:
    build: .
    command: node server.js
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/socketio_notifs
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo

  app2:
    build: .
    command: node server.js
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://mongo:27017/socketio_notifs
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - mongo

volumes:
  mongo_data:
